import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import Link from "next/link"
import IdleListener from "./IdleListener"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="zh">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <IdleListener />
        <nav style={{
          display: "flex",
          gap: 24,
          padding: "16px 32px",
          borderBottom: "1px solid #eee",
          marginBottom: 32,
          fontSize: 18
        }}>
          <Link href="/" style={{ textDecoration: "none" }}>日报编辑</Link>
          <Link href="/weekly" style={{ textDecoration: "none" }}>周报展示</Link>
          <Link href="/notify" style={{ textDecoration: "none" }}>系统通知</Link>
          <Link href="/dingtalk" style={{ textDecoration: "none" }}>钉钉推送</Link>
          <Link href="/template" style={{ textDecoration: "none" }}>模板管理</Link>
          <Link href="/monthly" style={{ textDecoration: "none" }}>月报导出</Link>
        </nav>
        {children}
      </body>
    </html>
  )
}
