name: "Tauri多平台发布"
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:  # 允许手动触发工作流

# 添加权限配置
permissions:
  contents: write

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.platform }}
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      
      - name: 安装Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - name: 安装Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: 安装 x86_64-apple-darwin target
        if: matrix.platform == 'macos-latest'
        run: rustup target add x86_64-apple-darwin
      
      - name: 安装Rust缓存
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
      
      - name: 安装依赖 (仅Ubuntu)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      
      - name: 安装前端依赖
        run: npm install
      
      - name: 构建应用
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # macOS签名设置 - 如需签名请取消注释并设置适当的secrets
          # APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          # APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          # APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
          # APPLE_ID: ${{ secrets.APPLE_ID }}
          # APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          # APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        with:
          tagName: ${{ github.ref_name }} # 自动使用推送的标签名
          releaseName: "日报助手 v__VERSION__" # __VERSION__将被自动替换为应用版本
          releaseBody: |
            此版本包含以下平台的安装包:
            - Windows (x64): .msi 和 .exe 安装包
            - macOS (Intel & Apple Silicon): .dmg 安装包
            - Linux: .AppImage 和 .deb 安装包
            
            请下载对应您操作系统的安装包进行安装。
          releaseDraft: true # 创建为草稿，允许发布前编辑
          prerelease: false # 不标记为预发布版本
          
          # 针对macOS平台的特殊构建参数 - 创建Universal Binary (同时支持Intel和Apple Silicon)
          args: ${{ matrix.platform == 'macos-latest' && '--target universal-apple-darwin' || '' }} 